### ISSUE TITLE
Handle missing configuration in plugin & add plugin to config check page

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms-ext-haalcentraal-hr#7]
https://github.com/open-formulieren/open-forms-ext-haalcentraal-hr/blob/6ba14238019948a14c550e0d7b439042a80219d8/prefill_haalcentraalhr/plugin.py#L74

`build_client` may return `None`, I would:

- add type annotations for this method
- explicitly handle the `is None` case instead of relying on the exception handler, and log that the service is not configured properly

Additionally, this plugin should also properly implement the config self test, you can use HR BRP as reference: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/prefill/contrib/haalcentraal/plugin.py#L153 and https://github.com/open-formulieren/open-forms/blob/master/src/openforms/prefill/contrib/haalcentraal/plugin.py#L173

**Comment by SilviaAmAm** [comment]
Todo:
- [x] Type annotations
- [x] Handle None case
- [x] Config test method
